import './style.less';
import 'jquery';
import _ from 'lodash';
import './components/form&elements/datepicker.min.js';
import './components/form&elements/dropdown-guest/dropdown-guest.js';
import './components/form&elements/dropdown-bed/dropdown-bed.js';
import './components/form&elements/checkbox-list/checkbox-list.js';
import './components/form&elements/checkbox-buttons/checkbox-buttons.js';
import './components/form&elements/radio-buttons/radio-buttons.js';
import './components/form&elements/like-button/like-button.js';