import './style.less';
import 'jquery';
import _ from 'lodash';
import './jquery-ui.min.js';
import './datepicker.js';
import './jquery.jcarousel.min.js'
import './components/form&elements/dropdown-guest/dropdown-guest.js';
import './components/form&elements/dropdown-bed/dropdown-bed.js';
import './components/form&elements/checkbox-list/checkbox-list.js';
import './components/form&elements/radio-buttons/radio-buttons.js';
import './components/form&elements/like-button/like-button.js';
import './components/form&elements/rate-button/rate-button-2.js';
import './components/form&elements/comments/comments.js';
import './components/form&elements/range-slider/range-slider.js';
import './components/form&elements/filter-date/filter-date.js';
import './components/form&elements/date-dropdown/date-dropdown.js';
import './components/cards/cards.js';
import './landing-page/main.js';
import './search-room-page/search-room-page.js';
import'./room-details/room-details.js';
